# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NodeidTransfer < Formula
  desc ""
  homepage ""
  version "0.1.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fs0414/nodeid-transfer/releases/download/v0.1.6/nodeid-transfer_Darwin_x86_64.tar.gz"
      sha256 "0ab1babb87117ced4ef5a8b1b276634a96541f86b3f8b5fd5f325cda807dc4fe"

      def install
        bin.install "nodeid-transfer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fs0414/nodeid-transfer/releases/download/v0.1.6/nodeid-transfer_Darwin_arm64.tar.gz"
      sha256 "48ae72ea7a820e318726f535d77aa3ab33de14ce525e83534e360b1675145017"

      def install
        bin.install "nodeid-transfer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fs0414/nodeid-transfer/releases/download/v0.1.6/nodeid-transfer_Linux_x86_64.tar.gz"
        sha256 "5ee2d4286c5e91c4e759f8e9a3cf8b7f1db9f774e8aef0b24e952d5bfecede55"

        def install
          bin.install "nodeid-transfer"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fs0414/nodeid-transfer/releases/download/v0.1.6/nodeid-transfer_Linux_arm64.tar.gz"
        sha256 "5a086c12249f127f324a95c95e10f99b0813442fc35316c562e5d0de81b75751"

        def install
          bin.install "nodeid-transfer"
        end
      end
    end
  end
end
