# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccsession < Formula
  desc "Fuzzy session picker for claude --resume"
  homepage "https://github.com/sorafujitani/ccsession"
  version "0.2.0"
  license "MIT"

  depends_on "fzf"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sorafujitani/ccsession/releases/download/v0.2.0/ccsession_0.2.0_darwin_amd64.tar.gz"
      sha256 "f125c6bd6c51730db7cd1b4b65bdfcb764c6ecee0d804b425e13d99f6c198926"

      define_method(:install) do
        bin.install "ccsession"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sorafujitani/ccsession/releases/download/v0.2.0/ccsession_0.2.0_darwin_arm64.tar.gz"
      sha256 "8317214f4655bbc39bdaf07a3d17f66e113e3ce58d2a3d3796b4677233ddcc43"

      define_method(:install) do
        bin.install "ccsession"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorafujitani/ccsession/releases/download/v0.2.0/ccsession_0.2.0_linux_amd64.tar.gz"
      sha256 "5b9115b174f859f313cd6587ea55b509dd23ff8b5f028d7afdadecad5dc06825"
      define_method(:install) do
        bin.install "ccsession"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorafujitani/ccsession/releases/download/v0.2.0/ccsession_0.2.0_linux_arm64.tar.gz"
      sha256 "4fa9bdce73b62aafd27d22a6fab7094a0e3b906395334aa34d9963244a94931a"
      define_method(:install) do
        bin.install "ccsession"
      end
    end
  end

  def caveats
    <<~EOS
      ccsession resumes sessions through the `claude` CLI (Claude Code), which
      is not distributed via Homebrew. Install it separately:
        https://docs.claude.com/en/docs/claude-code
    EOS
  end

  test do
    system "#{bin}/ccsession", "--version"
  end
end
