# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccsession < Formula
  desc "Fuzzy session picker for claude --resume"
  homepage "https://github.com/sorafujitani/ccsession"
  version "1.3.0"
  license "MIT"

  depends_on "fzf"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sorafujitani/ccsession/releases/download/v1.3.0/ccsession_1.3.0_darwin_amd64.tar.gz"
      sha256 "26d9f31a2aa89c573c40aa0db4c3c398b611fb7abe3e4ed507bfe20c32b6ae10"

      define_method(:install) do
        bin.install "ccsession"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sorafujitani/ccsession/releases/download/v1.3.0/ccsession_1.3.0_darwin_arm64.tar.gz"
      sha256 "27ec0deb6d103729a79927df1f899ce9bc53e7d53713c619a491fea4b9029096"

      define_method(:install) do
        bin.install "ccsession"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorafujitani/ccsession/releases/download/v1.3.0/ccsession_1.3.0_linux_amd64.tar.gz"
      sha256 "7d80cc592d34cd9edf30c87e41484d7da2358dcb066bd5e246ab6b7cee8845e1"
      define_method(:install) do
        bin.install "ccsession"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorafujitani/ccsession/releases/download/v1.3.0/ccsession_1.3.0_linux_arm64.tar.gz"
      sha256 "5b16e0166d0d4d47c4910b197a2e31c4c0f3c06342179705d432da576d98779b"
      define_method(:install) do
        bin.install "ccsession"
      end
    end
  end

  def caveats
    <<~EOS
      ccsession resumes sessions through the `claude` CLI (Claude Code), which
      is not distributed via Homebrew. Install it separately:
        https://docs.claude.com/en/docs/claude-code
    EOS
  end

  test do
    system "#{bin}/ccsession", "--version"
  end
end
