# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Policedoc < Formula
  desc "Check CLI examples in Markdown using installed executables"
  homepage "https://github.com/sorafujitani/police-doc"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sorafujitani/police-doc/releases/download/v0.1.0/policedoc_0.1.0_darwin_amd64.tar.gz"
      sha256 "dab3964db727dc37d0b9d9adeba565b528d6bf08bf369a02b4612162e8bf86cc"

      define_method(:install) do
        bin.install "policedoc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sorafujitani/police-doc/releases/download/v0.1.0/policedoc_0.1.0_darwin_arm64.tar.gz"
      sha256 "f4907595415ae8d98da30627818e9e3afb14d3dae36845804fd17da46718a7d9"

      define_method(:install) do
        bin.install "policedoc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorafujitani/police-doc/releases/download/v0.1.0/policedoc_0.1.0_linux_amd64.tar.gz"
      sha256 "033c29256f50f5b0d1f9b3a0f1feb391d2767956157cefb118aba70316041022"
      define_method(:install) do
        bin.install "policedoc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorafujitani/police-doc/releases/download/v0.1.0/policedoc_0.1.0_linux_arm64.tar.gz"
      sha256 "aaec7123645dba1b61bce80d015b49c9e7d22b4e39a60ced6590bae4ce3540d6"
      define_method(:install) do
        bin.install "policedoc"
      end
    end
  end

  test do
    assert_match "policedoc #{version}", shell_output("#{bin}/policedoc version")
  end
end
