# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Policedoc < Formula
  desc "Check CLI examples in Markdown using installed executables"
  homepage "https://github.com/sorafujitani/police-doc"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sorafujitani/police-doc/releases/download/v0.2.0/policedoc_0.2.0_darwin_amd64.tar.gz"
      sha256 "03fcebbf8d5e94e8471541021e6cfac05b43e6f5c63e1852466b475a168242e5"

      define_method(:install) do
        bin.install "policedoc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sorafujitani/police-doc/releases/download/v0.2.0/policedoc_0.2.0_darwin_arm64.tar.gz"
      sha256 "2b299f30924ed6cb9b57e9b5cf21a0441501656c5377d52bf6aaec9077ee2ede"

      define_method(:install) do
        bin.install "policedoc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorafujitani/police-doc/releases/download/v0.2.0/policedoc_0.2.0_linux_amd64.tar.gz"
      sha256 "8756255b4dc0b5206552a53406650713d130e5c65593b98dfb8c2b7b37a07f13"
      define_method(:install) do
        bin.install "policedoc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorafujitani/police-doc/releases/download/v0.2.0/policedoc_0.2.0_linux_arm64.tar.gz"
      sha256 "4d220361942afd4ec5953e92b2f1e21a46f77b9f68df9ae0d28a06b2665ac7b4"
      define_method(:install) do
        bin.install "policedoc"
      end
    end
  end

  test do
    assert_match "policedoc #{version}", shell_output("#{bin}/policedoc version")
  end
end
