# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WezKv < Formula
  desc "Fuzzy-searchable TUI viewer for wezterm keybindings"
  homepage "https://github.com/sorafujitani/wezterm-keymap-viewer"
  version "0.1.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sorafujitani/wez-kv/releases/download/v0.1.10/wkv_darwin_amd64.tar.gz"
      sha256 "89191b31247a313173840f3e3de5b4f1e134a56cc6e9db4c8c5fdca81682ad6c"

      def install
        bin.install "wkv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sorafujitani/wez-kv/releases/download/v0.1.10/wkv_darwin_arm64.tar.gz"
      sha256 "3db7034cfff050bc727289dcc366f8a4d3758aca1904d20acd65acba9e970ad1"

      def install
        bin.install "wkv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorafujitani/wez-kv/releases/download/v0.1.10/wkv_linux_amd64.tar.gz"
      sha256 "714b5314bc7ef81a6f08d5b5ec79bbf5a06005a90a4c033de545efd2415c56f6"
      def install
        bin.install "wkv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorafujitani/wez-kv/releases/download/v0.1.10/wkv_linux_arm64.tar.gz"
      sha256 "b4649b0c55bfb6c7ea33edb44fbb9996a20e6499c4518f81adf5ac33d1b77272"
      def install
        bin.install "wkv"
      end
    end
  end

  def caveats
    <<~EOS
      wkv requires wezterm to be installed and available in your PATH.
    EOS
  end
end
