# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WezKv < Formula
  desc "Fuzzy-searchable TUI viewer for wezterm keybindings"
  homepage "https://github.com/sorafujitani/wezterm-keymap-viewer"
  version "0.1.13"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sorafujitani/wez-kv/releases/download/v0.1.13/wkv_darwin_amd64.tar.gz"
      sha256 "d2265b9d395381d18f8b5f983d1e88eb8a3b1df588fc77ee318800e4f14f34fb"

      define_method(:install) do
        bin.install "wkv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sorafujitani/wez-kv/releases/download/v0.1.13/wkv_darwin_arm64.tar.gz"
      sha256 "7ea3e0da6f2341bec49b38c8514bf0421d1f40c302f28d064be45eead128fb6e"

      define_method(:install) do
        bin.install "wkv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorafujitani/wez-kv/releases/download/v0.1.13/wkv_linux_amd64.tar.gz"
      sha256 "1b38a66141e48f4d2db72ffcad769dafe154b2d55ccb24a00c50bcc85455d068"
      define_method(:install) do
        bin.install "wkv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorafujitani/wez-kv/releases/download/v0.1.13/wkv_linux_arm64.tar.gz"
      sha256 "45dcccbd3697890ff38396ca203a6208c5717a62e54318c1d8273f0518cb2e5a"
      define_method(:install) do
        bin.install "wkv"
      end
    end
  end

  def caveats
    <<~EOS
      wkv requires wezterm to be installed and available in your PATH.
    EOS
  end
end
