# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WezKv < Formula
  desc "Fuzzy-searchable TUI viewer for wezterm keybindings"
  homepage "https://github.com/sorafujitani/wezterm-keymap-viewer"
  version "0.1.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sorafujitani/wez-kv/releases/download/v0.1.11/wkv_darwin_amd64.tar.gz"
      sha256 "830d136f515fd11cfc8d26c21e787a0742a2a64fc21957aa485fc6d7d5ab9458"

      def install
        bin.install "wkv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sorafujitani/wez-kv/releases/download/v0.1.11/wkv_darwin_arm64.tar.gz"
      sha256 "181603c081b34e664c1e8f841651d80d918f9fd27ce2b72b65408693bce8b292"

      def install
        bin.install "wkv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorafujitani/wez-kv/releases/download/v0.1.11/wkv_linux_amd64.tar.gz"
      sha256 "0c1529fa813581f537552fc1674ecd65d99afe9da059472fe5bf27782d9b2c64"
      def install
        bin.install "wkv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorafujitani/wez-kv/releases/download/v0.1.11/wkv_linux_arm64.tar.gz"
      sha256 "2cb72727e34f431746d5d71d1b3a5d3765f5c446806d9f89ab35e9bfc8afc17a"
      def install
        bin.install "wkv"
      end
    end
  end

  def caveats
    <<~EOS
      wkv requires wezterm to be installed and available in your PATH.
    EOS
  end
end
