# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wkv < Formula
  desc "Fuzzy-searchable TUI viewer for wezterm keybindings"
  homepage "https://github.com/sorafujitani/wezterm-keymap-viewer"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sorafujitani/wez-kv/releases/download/v0.1.7/wkv_darwin_amd64.tar.gz"
      sha256 "dafeb5d25a61d2c5651c778487adf5d7c4f1f32825824ece62143cf4c1431161"

      def install
        bin.install "wkv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sorafujitani/wez-kv/releases/download/v0.1.7/wkv_darwin_arm64.tar.gz"
      sha256 "8ab6570fbc2a72b0383b928920af6cc6780362abf3d7ba88ec7be4aa1c2e1b64"

      def install
        bin.install "wkv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorafujitani/wez-kv/releases/download/v0.1.7/wkv_linux_amd64.tar.gz"
      sha256 "09c7592b4772656d03a8ed40480d31b1b7690d5b1cc0ed7dbbcbe6abb3c90c6a"
      def install
        bin.install "wkv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorafujitani/wez-kv/releases/download/v0.1.7/wkv_linux_arm64.tar.gz"
      sha256 "5d29097a94a6d757ae4d48732db235e07c50318acb9dcf5d5b6aac1d417e10e9"
      def install
        bin.install "wkv"
      end
    end
  end

  def caveats
    <<~EOS
      wkv requires wezterm to be installed and available in your PATH.
    EOS
  end
end
