# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wkv < Formula
  desc "Fuzzy-searchable TUI viewer for wezterm keybindings"
  homepage "https://github.com/sorafujitani/wezterm-keymap-viewer"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sorafujitani/wez-kv/releases/download/v0.1.5/wkv_darwin_amd64.tar.gz"
      sha256 "7b2c29354eab677b9848021ad76c9d42543245f3c9fa27ee38a68e3cafd4e363"

      def install
        bin.install "wkv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sorafujitani/wez-kv/releases/download/v0.1.5/wkv_darwin_arm64.tar.gz"
      sha256 "cad5e6e51ad11cea89e209fd86e7957dec978673a66c6059d3df1f86813b617b"

      def install
        bin.install "wkv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorafujitani/wez-kv/releases/download/v0.1.5/wkv_linux_amd64.tar.gz"
      sha256 "437ebef522da1adc9b4e84457d4c3fb52155a4bfb72b1e5d68030ea1be6a2f91"
      def install
        bin.install "wkv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorafujitani/wez-kv/releases/download/v0.1.5/wkv_linux_arm64.tar.gz"
      sha256 "602ad9cab0d0bb8ae6858eedfe464b765c3357e910dbdb9e2d92dc33b2b00d1a"
      def install
        bin.install "wkv"
      end
    end
  end

  def caveats
    <<~EOS
      wkv requires wezterm to be installed and available in your PATH.
    EOS
  end
end
